const test=require('node:test'),assert=require('node:assert/strict');
const {settings,decode,Dashboard,TripConsumption}=require('../src/model.cjs');
const {hit,Touch,Inputs}=require('../src/interaction.cjs');
const {drive}=require('./fixtures.cjs');
const cfg=settings();
test('SI speed conversion, gear and percentage',()=>{const v=new Dashboard().view(drive(),0,0,cfg);assert.equal(v.page,'drive');assert.ok(Math.abs(v.kmh-80)<0.001);assert.equal(v.gear,12);assert.equal(v.fuelPercent,65);});
test('instrument font and theme settings validate with legacy migration',()=>{assert.equal(settings().digitStyle,'rally');assert.equal(settings({digitStyle:'segment'}).digitStyle,'segment');assert.equal(settings({digitStyle:'din'}).digitStyle,'din');assert.equal(settings({digitStyle:'font'}).digitStyle,'rally');assert.equal(settings({theme:'el'}).theme,'el_mint');assert.equal(settings({theme:'el_amber'}).theme,'el_amber');});
test('manual hold cycles and brake hold are validated settings',()=>{assert.equal(settings().manualPageHoldCycles,3);assert.equal(settings({manualPageHoldCycles:5}).manualPageHoldCycles,5);assert.equal(settings({manualPageHoldCycles:4}).manualPageHoldCycles,3);assert.equal(settings({brakePageHoldSeconds:99}).brakePageHoldSeconds,20);});
test('moving drive keeps rotating panels while cruise state remains available to the status icon',()=>{const p=drive(),d=new Dashboard();p.values['truck.cruise_control']=22;assert.equal(d.view(p,0,0,cfg).page,'drive');assert.equal(d.view(p,15000,15000,cfg).panel,'route');});
test('stale data freezes cached readings and shutdown shows offline',()=>{const d=new Dashboard();const first=d.view(drive(),0,0,cfg);assert.equal(d.view(drive(),0,1500,cfg).p,first.p);assert.equal(d.view(drive(),0,1500,cfg).inputReady,false);const p=drive();p.connected=false;assert.equal(d.view(p,0,0,cfg).page,'offline');});
test('pause and binding mode input gates',()=>{const d=new Dashboard(),p=drive();p.paused=true;assert.equal(d.view(p,0,0,cfg).page,'paused');assert.equal(d.view(p,0,0,cfg).inputReady,false);assert.equal(d.view(p,0,0,{...cfg,bindingMode:true}).inputReady,true);});
test('reverse and stopped contexts do not replace or accelerate the default carousel',()=>{const c=settings({cycleSeconds:15}),d=new Dashboard(),p=drive();p.values['truck.displayed.gear']=-1;assert.equal(d.view(p,0,0,c).page,'reverse');p.values['truck.displayed.gear']=0;p.values['truck.speed']=0;
  let v=d.view(p,2100,2100,c);assert.equal(v.page,'drive');assert.equal(v.panel,'fuel');v=d.view(p,14999,14999,c);assert.equal(v.panel,'fuel');v=d.view(p,15000,15000,c);assert.equal(v.panel,'route');p.values['truck.speed']=2;assert.equal(d.view(p,16000,16000,c).page,'drive');});
test('manual pages remain visible for three complete carousel cycles and overlays pause their timer',()=>{const c=settings({cycleSeconds:5,manualPageHoldCycles:3}),d=new Dashboard(),p=drive();d.select('job',0,c);
  let v=d.view(p,0,0,c);assert.equal(v.page,'job');assert.equal(v.panel,'job_overview');v=d.view(p,5000,5000,c);assert.equal(v.panel,'job_timing');
  p.values['truck.brake.air.pressure.emergency']=1;v=d.view(p,7000,7000,c);assert.equal(v.page,'alert');const remaining=v.manualRemainingMs;v=d.view(p,10000,10000,c);assert.equal(v.manualRemainingMs,remaining);
  delete p.values['truck.brake.air.pressure.emergency'];v=d.view(p,10001,10001,c);assert.equal(v.page,'job');d.view(p,15001,15001,c);d.view(p,20001,20001,c);assert.equal(d.view(p,20002,20002,c).page,'drive');});
test('missing values are null, not zero, and trip handles loaded saves',()=>{const d=new Dashboard(),p=drive();delete p.values['fuel.capacity'];delete p.values['truck.speed'];let v=d.view(p,0,0,cfg);assert.equal(v.kmh,null);assert.equal(v.fuelPercent,null);p.values['truck.odometer']=12;v=d.view(p,0,0,cfg);assert.equal(v.trip,0);});
test('strict packet shape, invalid values and bounded size',()=>{assert.equal(decode(Buffer.from('{}')),null);assert.equal(decode(Buffer.alloc(17000)),null);const p=drive();p.values['truck.speed']='123';assert.equal(decode(Buffer.from(JSON.stringify(p))).values['truck.speed'],undefined);p.protocol=2;assert.equal(decode(Buffer.from(JSON.stringify(p))),null);});
test('destination strings are bounded and driving panels follow configured rotation',()=>{const p=drive(),decoded=decode(Buffer.from(JSON.stringify(p)));assert.equal(decoded.values['job.destination.city'],'Berlin');
  p.values.bad='x'.repeat(97);assert.equal(decode(Buffer.from(JSON.stringify(p))).values.bad,undefined);
  const d=new Dashboard(),c=settings({cycleSeconds:5,cyclePanels:['route','systems','route','invalid']});assert.equal(d.view(p,0,0,c).panel,'route');assert.equal(d.view(p,5000,5000,c).panel,'systems_engine');
  assert.deepEqual(c.cyclePanels,['route','systems']);assert.deepEqual(settings({cyclePanels:[]}).cyclePanels,['fuel','route','systems']);});
test('overspeed occupies alert page for three seconds then remains as a compact warning',()=>{const p=drive(),d=new Dashboard();p.values['truck.speed']=30;
  let v=d.view(p,0,0,cfg);assert.equal(v.page,'alert');assert.equal(v.overspeed,true);assert.ok(v.alerts.some(a=>a.id==='speed'));
  v=d.view(p,3001,3001,cfg);assert.equal(v.page,'drive');assert.equal(v.overspeed,true);assert.ok(!v.alerts.some(a=>a.id==='speed'));
  p.values['truck.speed']=20;v=d.view(p,3100,3100,cfg);assert.equal(v.overspeed,false);});
test('first fuel rise at rest immediately opens refueling; subsequent rises extend only the exit hold',()=>{const p=drive(),d=new Dashboard();p.values['truck.speed']=0;d.view(p,0,0,cfg);p.seq=2;p.values['truck.fuel.amount']+=1;
  assert.equal(d.view(p,100,100,cfg).refueling,true);p.seq=3;p.values['truck.fuel.amount']+=1;
  let v=d.view(p,300,300,cfg);assert.equal(v.refueling,true);assert.equal(v.panel,'fuel');assert.equal(d.view(p,2101,2101,cfg).refueling,false);});
test('job, trailer and truck panels use the configured common cycle',()=>{const p=drive(),d=new Dashboard(),c=settings({cycleSeconds:5,manualPageHoldCycles:3,cyclePanels:['systems']});
  d.select('job',0,c);assert.equal(d.view(p,0,0,c).panel,'job_overview');assert.equal(d.view(p,5000,5000,c).panel,'job_timing');assert.equal(d.view(p,10000,10000,c).panel,'job_distance');
  d.select('trailer',11000,c);assert.equal(d.view(p,11000,11000,c).panel,'trailer_status');assert.equal(d.view(p,16000,16000,c).panel,'trailer_damage');d.auto();
  assert.equal(d.view(p,20000,20000,c).panel,'systems_engine');assert.equal(d.view(p,25000,25000,c).panel,'systems_brake');});
test('braking overlay updates live, holds after release, and returns to the interrupted manual page',()=>{const p=drive(),d=new Dashboard(),c=settings({cycleSeconds:5,brakePageHoldSeconds:2});d.select('job',0,c);d.view(p,0,0,c);
  p.values['truck.input.brake']=.63;let v=d.view(p,100,100,c);assert.equal(v.page,'braking');assert.equal(v.brakeForce,.63);p.values['truck.input.brake']=0;
  assert.equal(d.view(p,1500,1500,c).page,'braking');v=d.view(p,2101,2101,c);assert.equal(v.page,'job');assert.ok(v.manualRemainingMs>14000);
  d.select('brake',2200,c);assert.equal(d.view(p,2200,2200,c).page,'brake');});
test('left selector cycles RALLY, CTRL and INFO without clearing a manual page',()=>{const d=new Dashboard(),p=drive();assert.equal(d.view(p,0,0,cfg).section,0);d.nextSection();assert.equal(d.view(p,1,1,cfg).section,1);d.select('job',1,cfg);d.nextSection();let v=d.view(p,2,2,cfg);assert.equal(v.section,2);assert.equal(v.page,'job');d.nextSection();assert.equal(d.view(p,3,3,cfg).page,'motion');assert.equal(d.section,3);d.nextSection();assert.equal(d.view(p,4,4,cfg).section,0);});
test('toll events queue for three visible seconds and wait behind warnings',()=>{const p=drive(),d=new Dashboard();p.values['event.toll.id']=1;p.values['event.toll.amount']=24;
  let v=d.view(p,0,0,cfg);assert.equal(v.page,'notice');assert.equal(v.tollNotice.amount,24);p.seq=2;p.values['event.toll.id']=2;p.values['event.toll.amount']=9;
  for(let now=250;now<=3000;now+=250)v=d.view(p,now,now,cfg);assert.equal(v.tollNotice.id,1);
  v=d.view(p,3250,3250,cfg);assert.equal(v.tollNotice.id,2);p.values['truck.brake.air.pressure.emergency']=1;
  v=d.view(p,3500,3500,cfg);assert.equal(v.page,'alert');const shown=v.tollNotice.shownMs;v=d.view(p,5000,5000,cfg);assert.equal(v.tollNotice.shownMs,shown);});
test('touch boundaries, release deduplication, movement and long press',()=>{assert.equal(hit(2170,20),undefined);assert.equal(hit(1630,20).id,'lights');const t=new Touch();t.event({state:'down',x:1500,y:20},0);assert.equal(t.event({state:'up',x:1500,y:20},1000).long,true);assert.equal(t.event({state:'end',x:1500,y:20},1001),null);t.event({state:'down',x:1500,y:20},2000);t.event({state:'pressing',x:1550,y:20},2010);assert.equal(t.event({state:'up',x:1500,y:20},2020),null);});
test('dangerous Quick Controls require their full hold and expose progress',()=>{const controls=[{id:'trailer',x:1450,w:120,bit:10,holdMs:800}],t=new Touch();
  t.event({state:'down',x:1500,y:20},0,controls);assert.equal(t.progress(400).value,0.5);assert.deepEqual(t.event({state:'up',x:1500,y:20},799,controls),{cancelled:true});
  t.event({state:'down',x:1500,y:20},1000,controls);assert.deepEqual(t.event({state:'pressing',x:1500,y:20},1800,controls),{feedback:true});
  const action=t.event({state:'up',x:1500,y:20},1801,controls);assert.equal(action.id,'trailer');assert.equal(action.bit,10);
});
test('input pulses expire and disabled state releases all buttons',()=>{const i=new Inputs();i.pulse(0,0);i.pulse(5,0);assert.equal(i.packet(100,true).readUInt32LE(4),33);assert.equal(i.packet(221,true).readUInt32LE(4),0);i.pulse(0,300);assert.equal(i.packet(301,false).readUInt32LE(4),0);});
test('all fourteen generic input bits are supported and higher bits are ignored',()=>{const i=new Inputs();i.pulse(13,0);i.pulse(14,0);assert.equal(i.packet(1,true).readUInt32LE(4),1<<13);});
test('trip fuel average uses fuel and distance, freezes at rest and rebases on refuel',()=>{const f=new TripConsumption();assert.equal(f.update(100,100,1),null);let shown;
  for(let n=1;n<=4;n++)shown=f.update(100-n*.03,100+n*.1,n+1);assert.ok(Math.abs(shown-30)<.01);
  assert.equal(f.update(99.7,100.4,10),shown,'idling fuel use is frozen');assert.equal(f.update(105,100.4,11),shown,'refuel preserves trip totals');
  assert.equal(f.update(104.9,110,12),shown,'teleport-sized distance rebases the sample');
});
test('warning queue rotates without losing priority or overspeed limit detail',()=>{const p=drive(),d=new Dashboard(),c=settings();p.values['truck.speed']=30;p.values['truck.fuel.warning']=1;p.values['truck.adblue.warning']=1;
  let v=d.view(p,0,0,c);assert.equal(v.activeAlert.id,'speed');assert.match(v.activeAlert.detail,/LIMIT 90 KM\/H/);assert.equal(v.alerts.length,3);
  v=d.view(p,2000,2000,c);assert.equal(v.activeAlert.id,'fuel');p.values['truck.speed']=20;v=d.view(p,2100,2100,c);assert.ok(!v.alerts.some(a=>a.id==='speed'));assert.equal(v.overspeed,false);
});
